name: 'Publish to NeoFS Github Action'
description: 'This action allows you publish files, tests reports, static web pages and etc. to NeoFS.'
author: 'KeithWeaver'
branding:
  icon: 'server'
  color: 'green'
runs:
  using: composite
  steps:
    - name: Download latest stable neofs-cli for uploading reports to NeoFS
      uses: dsaltares/fetch-gh-release-asset@1.1.1
      with:
        repo: 'nspcc-dev/neofs-node'
        version: 'tags/v0.38.1'
        file: 'neofs-cli-amd64'
        target: 'neofs-node-stable/neofs-cli'

    - name: Chmod latest stable neofs-cli
      shell: sh
      if: runner.os == 'Linux'
      run: |
        sudo chmod a+x neofs-cli
      working-directory: neofs

    - name: Enable stable neofs-cli
      shell: sh
      if: always()
      run: |
        echo "$(pwd)" >> $GITHUB_PATH
      working-directory: neofs

    - name: Create wallet
      shell: sh
      if: always()
      env:
        TEST_RESULTS_WALLET: ${{ secrets.TEST_RESULTS_WALLET }}
      run: |
        echo "$TEST_RESULTS_WALLET" | base64 -d > wallet.json
      working-directory: neofs

    - name: Define expiration
      shell: sh
      if: always()
      env:
        TEST_RESULTS_NEOFS_NETWORK_DOMAIN: ${{ vars.TEST_RESULTS_NEOFS_NETWORK_DOMAIN }}
        MASTER_EXPIRATION_PERIOD: ${{ vars.MASTER_EXPIRATION_PERIOD }}
        PR_EXPIRATION_PERIOD: ${{ vars.PR_EXPIRATION_PERIOD }}
        MANUAL_RUN_EXPIRATION_PERIOD: ${{ vars.MANUAL_RUN_EXPIRATION_PERIOD }}
        OTHER_EXPIRATION_PERIOD: ${{ vars.OTHER_EXPIRATION_PERIOD }}
      run: |
        CURRENT_EPOCH=$(neofs-cli netmap epoch --rpc-endpoint st1.$TEST_RESULTS_NEOFS_NETWORK_DOMAIN:8080)
        if [[ "${{ github.event_name }}" == "push" ]]; then
          EXP_EPOCH=$((MASTER_EXPIRATION_PERIOD + CURRENT_EPOCH))
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          EXP_EPOCH=$((PR_EXPIRATION_PERIOD + CURRENT_EPOCH))
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          EXP_EPOCH=0 # For test reports from releases - no expiration period
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          EXP_EPOCH=$((MANUAL_RUN_EXPIRATION_PERIOD + CURRENT_EPOCH))
        else
          EXP_EPOCH=$((OTHER_EXPIRATION_PERIOD + CURRENT_EPOCH))
        fi
        echo "EXP_EPOCH=$EXP_EPOCH" >> $GITHUB_ENV
      working-directory: neofs

    - name: Prepare test environment
      shell: sh
      id: prepare_venv
      run: |
        virtualenv --python=python3.11 venv
        source venv/bin/activate && pip install -r requirements.txt
      working-directory: neofs

    - name: Put files to NeoFS
      shell: sh
      id: put_files
      env:
        TEST_RESULTS_PASSWORD: ${{ secrets.TEST_RESULTS_PASSWORD }}
        TEST_RESULTS_NEOFS_NETWORK_DOMAIN: ${{ vars.TEST_RESULTS_NEOFS_NETWORK_DOMAIN }}
        TEST_RESULTS_CID: ${{ vars.TEST_RESULTS_CID }}
      run: |
        source venv.local-pytest/bin/activate && python ./push-to-neofs.py --expire-at $EXP_EPOCH \
        --neofs_domain $TEST_RESULTS_NEOFS_NETWORK_DOMAIN --run_id $RUN_ID --cid $TEST_RESULTS_CID \
        --files-dir ${GITHUB_WORKSPACE}/allure-report --wallet wallet.json
      working-directory: neofs
